### ISSUE TITLE
Rendre accessible la documentation des calculs

### ISSUE THREAD

**Issue by mquandalle** [incubateur-ademe/nosgestesclimat-site-nextjs#390]
Je regardais hier un live Twitch du Reveilleur. À un moment il a voulu comprendre comment nosgestesclimat calcule l'empreinte de la voiture : https://www.twitch.tv/videos/2075429795?t=2h40m11s

Ne sachant pas qu'il est possible d'explorer le détail des calculs, il est obligé de jouer avec les réponses et de faire de la "rétro-ingénerie" à partir des variations de résultat pour estimer les facteurs utilisés.

Je ne sais pas quelle serait la bonne manière d'exposer la documentation sur NGC. Sur mon-entreprise.urssaf.fr qui utilise aussi publicodes, la documentation est facilement découvrable en cliquant sur n'importe quel montant calculé. La difficulté c'est qu'une majorité d'utilisateurs serait sans doute perplexe en atterrissant par mégarde dans la documentation, mais que c'est une fonctionnalité précieuse pour une minorité d'utilisateurs plus curieux.

**Comment by jeannelf** [comment]
La mise en avant sur la page de fin permet deja beaucoup de clics sur la doc, les gens intéressés semblent s'y pencher, meme si en effet on n'est pas à 1/2 exceptions près :)
